# Generated by Django 4.2.5 on 2023-09-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
