# Generated by Django 4.2.5 on 2023-09-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_autor_cidade_alter_autor_nome_alter_autor_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='UF',
            field=models.CharField(max_length=20),
        ),
    ]
