# Generated by Django 4.2.5 on 2023-09-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cidade_uf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_de_publicacao',
            new_name='data_plub',
        ),
    ]
