# Generated by Django 4.2.5 on 2023-09-14 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_data_de_publicacao_livro_data_plub'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(default='2023-09-14'),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(default='Ficção', max_length=100),
        ),
    ]
