# Generated by Django 4.2.5 on 2023-09-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emprestimo_data_emprestimo_livro_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
