# Generated by Django 4.2.5 on 2023-09-25 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_livro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
