# Generated by Django 4.2.5 on 2023-09-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_livro_genero_alter_livro_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='autor',
            old_name='categoria',
            new_name='genero',
        ),
    ]
