# Generated by Django 4.2.5 on 2023-09-26 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('duracao', models.CharField(max_length=5)),
                ('sinopse', models.CharField(max_length=100)),
                ('site_oficial', models.CharField(max_length=40)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.BooleanField()),
                ('romance', models.BooleanField()),
                ('suspense', models.BooleanField()),
                ('cadastrar_genero', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciar_atores_e_diretores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('site', models.CharField(max_length=30)),
                ('instagram', models.CharField(max_length=20)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('nacionalidade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciar_episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('duracao', models.CharField(max_length=5)),
                ('data_disponibilizacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciar_paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.continente')),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciar_temporadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('duracao', models.CharField(max_length=5)),
                ('sinopse', models.CharField(max_length=100)),
                ('site_oficial', models.CharField(max_length=30)),
                ('data_lancamento', models.DateField()),
                ('nota_avaliacao', models.DecimalField(decimal_places=2, max_digits=2)),
                ('diretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_atores_e_diretores')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filme')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_paises')),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciar_serie_com_episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_episodio')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.serie')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_temporadas')),
            ],
        ),
        migrations.CreateModel(
            name='Gerenciar_com_atore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_atores_e_diretores')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.filme')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_atores_e_diretores'),
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genero'),
        ),
        migrations.AddField(
            model_name='filme',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gerenciar_paises'),
        ),
    ]
