# Generated by Django 4.2.5 on 2023-09-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avaliacao',
            new_name='Avaliacoe',
        ),
    ]
