# Generated by Django 4.2.5 on 2023-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_avaliacao_avaliacoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria_total',
            field=models.IntegerField(),
        ),
    ]
