# Generated by Django 4.2.7 on 2023-11-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DadosClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clima', models.CharField(max_length=30)),
                ('graus', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=2)),
                ('clima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clima')),
            ],
        ),
        migrations.CreateModel(
            name='Paise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='dadosclimaticos',
            name='pais',
        ),
        migrations.DeleteModel(
            name='Estados',
        ),
        migrations.DeleteModel(
            name='DadosClimaticos',
        ),
        migrations.AddField(
            model_name='dadosclimatico',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paise'),
        ),
        migrations.AlterField(
            model_name='continentes',
            name='paises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paise'),
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
