# Generated by Django 4.2.7 on 2023-11-06 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_clima_dadosclimatico_estado_paise_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paise',
            new_name='Pais',
        ),
    ]
