# Generated by Django 4.2.7 on 2023-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_estado_pais_delete_dadosclimatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
