# Generated by Django 4.2.7 on 2023-11-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_estado_temperatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperatura', models.FloatField()),
            ],
        ),
    ]
