# Generated by Django 4.2.7 on 2023-11-14 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pontomapa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PontoMapa',
        ),
    ]
