# Generated by Django 4.2.7 on 2023-11-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_pontomapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continentes',
            name='paises',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.pais'),
        ),
    ]
