# Generated by Django 4.2.7 on 2023-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
