# Generated by Django 5.0 on 2023-12-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_causa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='Estado',
        ),
        migrations.AddField(
            model_name='causa',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='causas', to='app.estado'),
            preserve_default=False,
        ),
    ]
